//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Necnat.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SwalLocalizer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SwalLocalizer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Necnat.Shared.Resources.SwalLocalizer", typeof(SwalLocalizer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action canceled..
        /// </summary>
        public static string Action_canceled_ {
            get {
                return ResourceManager.GetString("Action canceled.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred..
        /// </summary>
        public static string An_unexpected_error_has_occurred_ {
            get {
                return ResourceManager.GetString("An unexpected error has occurred.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Are_you_sure_ {
            get {
                return ResourceManager.GetString("Are you sure?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled!.
        /// </summary>
        public static string Canceled_ {
            get {
                return ResourceManager.GetString("Canceled!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to execute this action?.
        /// </summary>
        public static string Do_you_really_want_to_execute_this_action_ {
            get {
                return ResourceManager.GetString("Do you really want to execute this action?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error_ {
            get {
                return ResourceManager.GetString("Error!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information!.
        /// </summary>
        public static string Information_ {
            get {
                return ResourceManager.GetString("Information!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Cancel.
        /// </summary>
        public static string No__Cancel {
            get {
                return ResourceManager.GetString("No. Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question!.
        /// </summary>
        public static string Question_ {
            get {
                return ResourceManager.GetString("Question!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success_ {
            get {
                return ResourceManager.GetString("Success!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are invalid fields..
        /// </summary>
        public static string There_are_invalid_fields_ {
            get {
                return ResourceManager.GetString("There are invalid fields.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Warning_ {
            get {
                return ResourceManager.GetString("Warning!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes. Execute.
        /// </summary>
        public static string Yes__Execute {
            get {
                return ResourceManager.GetString("Yes. Execute", resourceCulture);
            }
        }
    }
}
